# Generated by Django 3.1.7 on 2021-02-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210227_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=60)),
                ('floor_apt', models.CharField(max_length=15)),
                ('address_line', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AddressGeoCodingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('geocoding_result_type', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('region_code', models.CharField(max_length=15)),
                ('administrative_area', models.CharField(max_length=40)),
                ('neighbourhood', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=30)),
                ('map_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField())
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='geocoding',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.addressgeocodingresult'),
        ),
    ]
