# Generated by Django 3.1.7 on 2021-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210228_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='confidence',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
