# Generated by Django 3.1.7 on 2021-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='addressgeocodingresult',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
