# Generated by Django 3.1.7 on 2021-02-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['updated_at']},
        ),
    ]
