# Generated by Django 3.1.7 on 2021-02-28 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210228_1056'),
        ('carts', '0002_auto_20210228_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Cart id')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aws', 'awaiting-peers'), ('pip', 'pending-initial-payment'), ('cmp', 'completed'), ('cnc', 'cancelled')], max_length=3)),
                ('clients_target', models.PositiveSmallIntegerField()),
                ('current_confirmed_clients', models.PositiveSmallIntegerField()),
                ('discount_amount', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='carts.cart')),
                ('shipmentAreaCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.address')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
