# Generated by Django 3.1.7 on 2021-03-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('purchases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.address'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='carts.cart'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipment_area_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.address'),
        ),
        migrations.AddField(
            model_name='individualpurchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_purchases', to='users.client'),
        ),
        migrations.AddField(
            model_name='individualpurchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.payment'),
        ),
        migrations.AddField(
            model_name='individualpurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_purchases', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='individualpurchase',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.shipment'),
        ),
    ]
