# Generated by Django 3.1.7 on 2021-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='shipmentAreaCenter',
            new_name='shipment_area_center',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='current_confirmed_clients',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('aws', 'awaiting-peers'), ('pip', 'pending-initial-payment'), ('cmp', 'completed'), ('cnc', 'cancelled')], default='aws', max_length=3),
        ),
    ]
