# Generated by Django 3.1.7 on 2021-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210228_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('aws', 'awaiting-peers'), ('pip', 'pending-initial-payment'), ('cmp', 'completed'), ('cnc', 'cancelled')], default='pip', max_length=3),
        ),
    ]
