# Generated by Django 3.1.7 on 2021-02-28 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210228_1539'),
        ('purchases', '0003_auto_20210228_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Payment id')),
                ('status', models.CharField(choices=[('pen', 'pending'), ('fld', 'failed'), ('rsv', 'reserved'), ('cap', 'captured')], default='pen', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Purchase id'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Shipment id')),
                ('status', models.CharField(choices=[('awp', 'awaiting-payment'), ('pen', 'pending'), ('apc', 'awaiting-purchase-completition'), ('dis', 'dispatched'), ('del', 'del'), ('abr', 'abr')], default='pen', max_length=3)),
                ('shipment_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Individual purchase id')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_purchases', to='users.client')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.payment')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_purchases', to='purchases.purchase')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.shipment')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
