# Generated by Django 3.1.7 on 2021-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20210301_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago')], max_length=15),
        ),
    ]
