# Generated by Django 3.1.7 on 2021-03-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20210301_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='vendor_id',
            new_name='vendor_payment_id',
        ),
    ]
