# Generated by Django 3.1.7 on 2021-03-01 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210228_1539'),
        ('purchases', '0005_remove_purchase_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.address'),
        ),
    ]
