# Generated by Django 3.1.7 on 2021-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20210228_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('awp', 'awaiting-payment'), ('pen', 'pending'), ('apc', 'awaiting-purchase-completition'), ('dis', 'dispatched'), ('del', 'del'), ('abr', 'abr')], default='awp', max_length=3),
        ),
    ]
