# Generated by Django 3.1.7 on 2021-03-02 22:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_auto_20210302_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.coupon'),
        ),
    ]
