# Generated by Django 3.1.7 on 2021-03-03 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20210302_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
