# Generated by Django 3.1.7 on 2021-03-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_coupon_valid_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_until']},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Coupon id'),
        ),
    ]
