# Generated by Django 3.1.7 on 2021-03-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_auto_20210303_0004'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='individualpurchase',
            index=models.Index(fields=['client'], name='client_idx'),
        ),
    ]
