# Generated by Django 3.1.7 on 2021-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_auto_20210303_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pen', 'pending'), ('fld', 'failed'), ('rsv', 'reserved'), ('cap', 'captured'), ('can', 'cancelled')], default='pen', max_length=3),
        ),
    ]
