# Generated by Django 3.1.7 on 2021-02-26 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('featured_photo_url', models.URLField()),
                ('photo_url', models.URLField()),
                ('unitary_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'El numero debe ser mayor a 0')])),
                ('measure_unit', models.CharField(choices=[('kg', 'kilogramo'), ('un', 'unidad'), ('at', 'atado')], max_length=3)),
                ('current_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'El numero debe ser mayor a 0')])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('commentary', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Not Good'), (3, 'Good'), (4, 'Excelent'), (5, 'Perfect')])),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
